;; Generated by repo-forge new --archetype rust-substrate-workspace-tool
;; Edit this file + run `repo-forge migrate .` to rewrite artifacts.

(defrepo tear
  :description "Rust-native tmux-compatible terminal multiplexer with typed shikumi config"
  :kind :rust-workspace-tool
  :visibility :private
  :binary "tear"
  :package-name "tear"
  :workspace-members ("tear-types" "tear-core" "tear-daemon" "tear-client" "tear-tmux-backend" "tear")
;; archetype: rust-substrate-workspace-tool
;; bindings:
;;   name = "tear"
;;   description = "Rust-native tmux-compatible terminal multiplexer with typed shikumi config"
;;   toolName = "tear"
;;   packageName = "tear"
;;   workspaceMembers = "tear-types,tear-core,tear-daemon,tear-client,tear-tmux-backend,tear"
)
